runner:
  model_name: "amazon_din"
  train_data_dir: "../../datasets/amazonelec/train"
  train_reader_path: "dinReader" # importlib format
  use_gpu: True
  use_auc: True
  train_batch_size: 32
  epochs: 1
  print_interval: 1000
  #model_init_path: "output_model/0" # init model
  model_save_path: "output_model_all_din"

# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    class: SGD
    learning_rate_base_lr: 0.85
    strategy: async
  # user-defined <key, value> pairs
  use_DataLoader: True
  item_emb_size: 64
  cat_emb_size: 64
  is_sparse: False
  item_count: 63001
  cat_count: 801
  act: "sigmoid"
