runner:
  model_name: "amazon_dien"
  train_data_dir: "data/train_data"
  train_reader_path: "dien_reader"
  use_gpu: False
  # use_cpu: False
  use_auc: True
  train_batch_size: 32
  epochs: 100
  print_interval: 1
  #model_init_path: "output_model/0" # init model
  model_save_path: "output_model_dien"
  infer_batch_size: 32 #100
  infer_reader_path: "dien_reader" # importlib format
  test_data_dir: "data/train_data"
  infer_load_path: "output_model_dien"
  infer_start_epoch: 0
  infer_end_epoch: 1

# hyper parameters of user-defined network
hyper_parameters:
  optimizer:
    class: SGD
    learning_rate_base_lr: 0.85 
    strategy: async
  use_DataLoader: True
  item_emb_size: 64
  cat_emb_size: 64
  is_sparse: False
  item_count: 63001
  cat_count: 801
  act: "sigmoid"
  distributed_embedding: 0
