runner:
  #train_data_dir: "data/slot_train_data_full"
  model_name: "criteo_widedeep"
  train_data_dir: "../../datasets/criteo/slot_train_data_full"
  train_reader_path: "criteo_reader" # importlib format
  use_gpu: True
  use_auc: True
  train_batch_size: 512
  epochs: 1
  print_interval: 1000
  #model_init_path: "output_model/0" # init model
  model_save_path: "output_model_all_wide_deep"

# hyper parameters of user-defined network
hyper_parameters:
  # optimizer config
  optimizer:
    class: Adam
    learning_rate: 0.001
    strategy: async
  # user-defined <key, value> pairs
  sparse_inputs_slots: 27
  sparse_feature_number: 1000001
  sparse_feature_dim: 32
  dense_input_dim: 13
  fc_sizes: [512, 256, 128, 32]
  distributed_embedding: 0
